name: Pipeline

on: [push]
env:
  APPLICATION_NAME: app2
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code!
      uses: actions/checkout@v1
    
    - name: Setup Python environment
      uses: actions/setup-python@v1.1.1
      with:
        python-version: '3.12.1'
        architecture: 'x64'

    - name: Set up environment
      run: echo "pythonLocation=/opt/hostedtoolcache/Python/3.12.1/x64" >> $GITHUB_ENV

    - name: Install requirements
      run: pip install --quiet --requirement requirements.txt

    - name: Lint code
      run: |
        flake8 --ignore=E501,E231 *.py
        pylint --disable=C0301 --disable=C0326 *.py
    - name: Run unit tests
      run: |
        python -m unittest --verbose --failfast
